version: '3'

services:
  db:
    image: postgres:14-alpine3.15
    container_name: users_storage
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
  
  app:
    build: .
    container_name: Geo-Service
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - db
