version: '3'

services:
  db:
    image: postgres:14-alpine3.15
    container_name: users_storage
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"

  user:
    build: ./user
    container_name: user
    depends_on:
      - db
    ports:
      - "8070:8070"


  auth:
    build: ./auth
    container_name: auth
    depends_on:
      - user
    ports:
      - "8050:8050"


  geo:
    build: ./geo
    container_name: geo
    ports:
      - "8060:8060"

  proxy:
    build: ./proxy
    container_name: proxy
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - user
      - auth
      - geo

