// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.12.4
// source: geo_provider.proto

package grpc_geo_provider

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Address struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	City   string `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	Street string `protobuf:"bytes,2,opt,name=street,proto3" json:"street,omitempty"`
	House  string `protobuf:"bytes,3,opt,name=house,proto3" json:"house,omitempty"`
	Lat    string `protobuf:"bytes,4,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon    string `protobuf:"bytes,5,opt,name=lon,proto3" json:"lon,omitempty"`
}

func (x *Address) Reset() {
	*x = Address{}
	if protoimpl.UnsafeEnabled {
		mi := &file_geo_provider_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_geo_provider_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_geo_provider_proto_rawDescGZIP(), []int{0}
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *Address) GetHouse() string {
	if x != nil {
		return x.House
	}
	return ""
}

func (x *Address) GetLat() string {
	if x != nil {
		return x.Lat
	}
	return ""
}

func (x *Address) GetLon() string {
	if x != nil {
		return x.Lon
	}
	return ""
}

type AddressSearchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Input string `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
}

func (x *AddressSearchRequest) Reset() {
	*x = AddressSearchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_geo_provider_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddressSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressSearchRequest) ProtoMessage() {}

func (x *AddressSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geo_provider_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressSearchRequest.ProtoReflect.Descriptor instead.
func (*AddressSearchRequest) Descriptor() ([]byte, []int) {
	return file_geo_provider_proto_rawDescGZIP(), []int{1}
}

func (x *AddressSearchRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

type AddressSearchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addresses []*Address `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
}

func (x *AddressSearchResponse) Reset() {
	*x = AddressSearchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_geo_provider_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddressSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressSearchResponse) ProtoMessage() {}

func (x *AddressSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_geo_provider_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressSearchResponse.ProtoReflect.Descriptor instead.
func (*AddressSearchResponse) Descriptor() ([]byte, []int) {
	return file_geo_provider_proto_rawDescGZIP(), []int{2}
}

func (x *AddressSearchResponse) GetAddresses() []*Address {
	if x != nil {
		return x.Addresses
	}
	return nil
}

type GeoCodeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lat string `protobuf:"bytes,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lng string `protobuf:"bytes,2,opt,name=lng,proto3" json:"lng,omitempty"`
}

func (x *GeoCodeRequest) Reset() {
	*x = GeoCodeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_geo_provider_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GeoCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoCodeRequest) ProtoMessage() {}

func (x *GeoCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_geo_provider_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoCodeRequest.ProtoReflect.Descriptor instead.
func (*GeoCodeRequest) Descriptor() ([]byte, []int) {
	return file_geo_provider_proto_rawDescGZIP(), []int{3}
}

func (x *GeoCodeRequest) GetLat() string {
	if x != nil {
		return x.Lat
	}
	return ""
}

func (x *GeoCodeRequest) GetLng() string {
	if x != nil {
		return x.Lng
	}
	return ""
}

type GeoCodeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addresses []*Address `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
}

func (x *GeoCodeResponse) Reset() {
	*x = GeoCodeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_geo_provider_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GeoCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoCodeResponse) ProtoMessage() {}

func (x *GeoCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_geo_provider_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoCodeResponse.ProtoReflect.Descriptor instead.
func (*GeoCodeResponse) Descriptor() ([]byte, []int) {
	return file_geo_provider_proto_rawDescGZIP(), []int{4}
}

func (x *GeoCodeResponse) GetAddresses() []*Address {
	if x != nil {
		return x.Addresses
	}
	return nil
}

var File_geo_provider_proto protoreflect.FileDescriptor

var file_geo_provider_proto_rawDesc = []byte{
	0x0a, 0x12, 0x67, 0x65, 0x6f, 0x5f, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2e, 0x41, 0x72, 0x74, 0x65, 0x6e, 0x73, 0x6f, 0x2e, 0x47, 0x65, 0x6f, 0x5f, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x67, 0x65, 0x6f, 0x2e, 0x61, 0x70, 0x69, 0x22, 0x6f, 0x0a, 0x07,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x69, 0x74, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x74, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x74, 0x72, 0x65, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x72,
	0x65, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x61, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6c, 0x61, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6c,
	0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6c, 0x6f, 0x6e, 0x22, 0x2c, 0x0a,
	0x14, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x22, 0x66, 0x0a, 0x15, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4d, 0x0a, 0x09, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x41, 0x72, 0x74, 0x65, 0x6e, 0x73, 0x6f, 0x2e, 0x47, 0x65, 0x6f,
	0x5f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x67, 0x65, 0x6f, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x09, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x65, 0x73, 0x22, 0x34, 0x0a, 0x0e, 0x47, 0x65, 0x6f, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6c, 0x61, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6e, 0x67, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6c, 0x6e, 0x67, 0x22, 0x60, 0x0a, 0x0f, 0x47, 0x65, 0x6f,
	0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4d, 0x0a, 0x09,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x2f, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x41, 0x72, 0x74,
	0x65, 0x6e, 0x73, 0x6f, 0x2e, 0x47, 0x65, 0x6f, 0x5f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x67, 0x65, 0x6f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x52, 0x09, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x32, 0x98, 0x02, 0x0a, 0x0b,
	0x47, 0x65, 0x6f, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x12, 0x8c, 0x01, 0x0a, 0x0d,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x3c, 0x2e,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x41, 0x72, 0x74, 0x65, 0x6e,
	0x73, 0x6f, 0x2e, 0x47, 0x65, 0x6f, 0x5f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x67,
	0x65, 0x6f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x3d, 0x2e, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x41, 0x72, 0x74, 0x65, 0x6e, 0x73, 0x6f,
	0x2e, 0x47, 0x65, 0x6f, 0x5f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x67, 0x65, 0x6f,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x53, 0x65, 0x61, 0x72,
	0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x7a, 0x0a, 0x07, 0x47, 0x65,
	0x6f, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x36, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2e, 0x41, 0x72, 0x74, 0x65, 0x6e, 0x73, 0x6f, 0x2e, 0x47, 0x65, 0x6f, 0x5f, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x67, 0x65, 0x6f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47,
	0x65, 0x6f, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x37, 0x2e,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x41, 0x72, 0x74, 0x65, 0x6e,
	0x73, 0x6f, 0x2e, 0x47, 0x65, 0x6f, 0x5f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x67,
	0x65, 0x6f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x47, 0x65, 0x6f, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x3a, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x41, 0x72, 0x74, 0x65, 0x6e, 0x73, 0x6f, 0x2f, 0x47, 0x65, 0x6f,
	0x2d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x67, 0x65, 0x6f, 0x2f, 0x70, 0x6b, 0x67,
	0x2f, 0x67, 0x72, 0x70, 0x63, 0x5f, 0x67, 0x65, 0x6f, 0x5f, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64,
	0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_geo_provider_proto_rawDescOnce sync.Once
	file_geo_provider_proto_rawDescData = file_geo_provider_proto_rawDesc
)

func file_geo_provider_proto_rawDescGZIP() []byte {
	file_geo_provider_proto_rawDescOnce.Do(func() {
		file_geo_provider_proto_rawDescData = protoimpl.X.CompressGZIP(file_geo_provider_proto_rawDescData)
	})
	return file_geo_provider_proto_rawDescData
}

var file_geo_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_geo_provider_proto_goTypes = []interface{}{
	(*Address)(nil),               // 0: github.com.Artenso.Geo_Service.geo.api.Address
	(*AddressSearchRequest)(nil),  // 1: github.com.Artenso.Geo_Service.geo.api.AddressSearchRequest
	(*AddressSearchResponse)(nil), // 2: github.com.Artenso.Geo_Service.geo.api.AddressSearchResponse
	(*GeoCodeRequest)(nil),        // 3: github.com.Artenso.Geo_Service.geo.api.GeoCodeRequest
	(*GeoCodeResponse)(nil),       // 4: github.com.Artenso.Geo_Service.geo.api.GeoCodeResponse
}
var file_geo_provider_proto_depIdxs = []int32{
	0, // 0: github.com.Artenso.Geo_Service.geo.api.AddressSearchResponse.addresses:type_name -> github.com.Artenso.Geo_Service.geo.api.Address
	0, // 1: github.com.Artenso.Geo_Service.geo.api.GeoCodeResponse.addresses:type_name -> github.com.Artenso.Geo_Service.geo.api.Address
	1, // 2: github.com.Artenso.Geo_Service.geo.api.GeoProvider.AddressSearch:input_type -> github.com.Artenso.Geo_Service.geo.api.AddressSearchRequest
	3, // 3: github.com.Artenso.Geo_Service.geo.api.GeoProvider.GeoCode:input_type -> github.com.Artenso.Geo_Service.geo.api.GeoCodeRequest
	2, // 4: github.com.Artenso.Geo_Service.geo.api.GeoProvider.AddressSearch:output_type -> github.com.Artenso.Geo_Service.geo.api.AddressSearchResponse
	4, // 5: github.com.Artenso.Geo_Service.geo.api.GeoProvider.GeoCode:output_type -> github.com.Artenso.Geo_Service.geo.api.GeoCodeResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_geo_provider_proto_init() }
func file_geo_provider_proto_init() {
	if File_geo_provider_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_geo_provider_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Address); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_geo_provider_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddressSearchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_geo_provider_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddressSearchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_geo_provider_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GeoCodeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_geo_provider_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GeoCodeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_geo_provider_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_geo_provider_proto_goTypes,
		DependencyIndexes: file_geo_provider_proto_depIdxs,
		MessageInfos:      file_geo_provider_proto_msgTypes,
	}.Build()
	File_geo_provider_proto = out.File
	file_geo_provider_proto_rawDesc = nil
	file_geo_provider_proto_goTypes = nil
	file_geo_provider_proto_depIdxs = nil
}
